vlog -work work /home/radsfer/college/Projeto MC1/simulation/modelsim/REGISTER32bit.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.BANK_vlg_vec_tst
onerror {resume}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[7]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[6]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[5]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[4]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[3]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[2]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[1]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[0]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[31]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[30]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[29]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[28]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[27]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[26]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[25]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[24]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[23]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[22]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[21]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[20]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[19]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[18]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[17]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[16]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[15]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[14]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[13]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[12]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[11]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[10]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[9]}
add wave {BANK_vlg_vec_tst/i1/IN_LOAD[8]}
add wave {BANK_vlg_vec_tst/i1/IN_C}
add wave {BANK_vlg_vec_tst/i1/IN_C[31]}
add wave {BANK_vlg_vec_tst/i1/IN_C[30]}
add wave {BANK_vlg_vec_tst/i1/IN_C[29]}
add wave {BANK_vlg_vec_tst/i1/IN_C[28]}
add wave {BANK_vlg_vec_tst/i1/IN_C[27]}
add wave {BANK_vlg_vec_tst/i1/IN_C[26]}
add wave {BANK_vlg_vec_tst/i1/IN_C[25]}
add wave {BANK_vlg_vec_tst/i1/IN_C[24]}
add wave {BANK_vlg_vec_tst/i1/IN_C[23]}
add wave {BANK_vlg_vec_tst/i1/IN_C[22]}
add wave {BANK_vlg_vec_tst/i1/IN_C[21]}
add wave {BANK_vlg_vec_tst/i1/IN_C[20]}
add wave {BANK_vlg_vec_tst/i1/IN_C[19]}
add wave {BANK_vlg_vec_tst/i1/IN_C[18]}
add wave {BANK_vlg_vec_tst/i1/IN_C[17]}
add wave {BANK_vlg_vec_tst/i1/IN_C[16]}
add wave {BANK_vlg_vec_tst/i1/IN_C[15]}
add wave {BANK_vlg_vec_tst/i1/IN_C[14]}
add wave {BANK_vlg_vec_tst/i1/IN_C[13]}
add wave {BANK_vlg_vec_tst/i1/IN_C[12]}
add wave {BANK_vlg_vec_tst/i1/IN_C[11]}
add wave {BANK_vlg_vec_tst/i1/IN_C[10]}
add wave {BANK_vlg_vec_tst/i1/IN_C[9]}
add wave {BANK_vlg_vec_tst/i1/IN_C[8]}
add wave {BANK_vlg_vec_tst/i1/IN_C[7]}
add wave {BANK_vlg_vec_tst/i1/IN_C[6]}
add wave {BANK_vlg_vec_tst/i1/IN_C[5]}
add wave {BANK_vlg_vec_tst/i1/IN_C[4]}
add wave {BANK_vlg_vec_tst/i1/IN_C[3]}
add wave {BANK_vlg_vec_tst/i1/IN_C[2]}
add wave {BANK_vlg_vec_tst/i1/IN_C[1]}
add wave {BANK_vlg_vec_tst/i1/IN_C[0]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[31]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[30]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[29]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[28]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[27]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[26]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[25]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[24]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[23]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[22]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[21]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[20]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[19]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[18]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[17]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[16]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[15]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[14]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[13]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[12]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[11]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[10]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[9]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[8]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[7]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[6]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[5]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[4]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[3]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[2]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[1]}
add wave {BANK_vlg_vec_tst/i1/IN_MEM[0]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[31]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[30]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[29]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[28]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[27]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[26]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[25]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[24]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[23]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[22]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[21]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[20]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[19]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[18]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[17]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[16]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[15]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[14]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[13]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[12]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[11]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[10]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[9]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[8]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[7]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[6]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[5]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[4]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[3]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[2]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[1]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT[0]}
add wave {BANK_vlg_vec_tst/i1/CLOCK}
add wave {BANK_vlg_vec_tst/i1/IN_SELECT}
add wave {BANK_vlg_vec_tst/i1/LOAD}
add wave {BANK_vlg_vec_tst/i1/OUT_EN}
add wave {BANK_vlg_vec_tst/i1/OUT_MEM_EN}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[31]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[30]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[29]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[28]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[27]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[26]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[25]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[24]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[23]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[22]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[21]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[20]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[19]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[18]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[17]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[16]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[15]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[14]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[13]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[12]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[11]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[10]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[9]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[8]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[7]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[6]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[5]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[4]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[3]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[2]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[1]}
add wave {BANK_vlg_vec_tst/i1/OUTPUT_MEM[0]}
add wave {BANK_vlg_vec_tst/i1/WRITE_EN}
run -all
